spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: MovieService
          uri: http://localhost:8082
          predicates:
            - Path=/api/movies/**
        - id: DirectorService
          uri: http://localhost:8083
          predicates:
            - Path=/api/directors/**

